---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "k8vent.fullname" . }}
  labels:
    app: {{ template "k8vent.name" . }}
    chart: {{ template "k8vent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "k8vent.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "k8vent.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "k8vent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with (include "k8vent.env" .) }}
            - name: ATOMIST_ENVIRONMENT
              value: {{ quote . }}
          {{- end }}
          {{- with (include "k8vent.workspaces" .) }}
          {{- $baseURL := "https://webhook.atomist.com/atomist/kube/teams/"}}
            - name: K8VENT_WEBHOOKS
              value: "{{ $baseURL }}{{ splitList "," . | join (printf ",%s" $baseURL) }}"
          {{- end }}
          {{- if eq (include "k8vent.mode" .) "namespace" }}
            - name: K8VENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
