{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if eq .Values.global.mode "cluster" }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ template "k8vent.fullname" . }}
  labels:
    app: {{ template "k8vent.name" . }}
    chart: {{ template "k8vent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if eq .Values.global.mode "cluster" }}Cluster{{ end }}Role
  name: {{ template "k8vent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8vent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
