{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8vent.serviceAccountName" . }}
  labels:
    app: {{ template "k8vent.name" . }}
    chart: {{ template "k8vent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
