apiVersion: v1
name: k8vent
version: 0.5.0
description: A Helm chart for k8vent
keywords:
  - kubernetes
  - atomist
home: https://github.com/atomist/k8vent/
maintainers:
  - name: Atomist
    email: support@atomist.com
    url: https://github.com/atomist
icon: https://images.atomist.com/logo/atomist-color-mark-transparent-small.png
appVersion: 0.10.0
