{{- $kube := set .Values.config.kubernetes "mode" (include "k8-automation.mode" .) -}}
{{- $config := set .Values.config "environment" (include "k8-automation.env" .) -}}
{{- $config := set .Values.config "workspaceIds" (include "k8-automation.workspaces" . | splitList ",") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8-automation.fullname" . }}
  labels:
    app: {{ template "k8-automation.name" . }}
    chart: {{ template "k8-automation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: {{ toJson $config | squote }}
