{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ template "k8-automation.role" . }}Binding
metadata:
  name: {{ template "k8-automation.fullname" . }}
  labels:
    app: {{ template "k8-automation.name" . }}
    chart: {{ template "k8-automation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8-automation.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ template "k8-automation.role" . }}
  name: {{ template "k8-automation.fullname" . }}
{{ end -}}
