{{- $secret := set .Values.secret "token" (include "k8-automation.token" . ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8-automation.fullname" . }}
  labels:
    app: {{ template "k8-automation.name" . }}
    chart: {{ template "k8-automation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config: {{ toJson $secret | b64enc }}
